name: Production Deployment

# Запуск СТРОГО вручную из веб-интерфейса GitHub
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22 # <--- ЕСЛИ ПРОБРОШЕН ДРУГОЙ ПОРТ, ПОМЕНЯЙ ЕГО ТУТ (например: 2222)
          script_stop: true
          script: |
            # Переходим в твой RAID-массив, где лежит проект
            cd /mnt/raid1/OpenChemDb
            
            echo "--- Подтягиваем свежий код из Git ---"
            git pull origin main
            
            echo "--- Запускаем сборку и миграции через Makefile ---"
            make update